forest:
  bean-id: config0 # ?spring????bean?id, ????forestConfiguration
  backend: okhttp3 # ??HTTP API? okhttp3 ???`okhttp3`/`httpclient`?
  max-connections: 1000 # ?????????????500
  max-route-connections: 500 # ???????????????500
  timeout: 3000 # ????????????, ????3000
  connect-timeout: 3000 # ????????????, ????2000
  retry-count: 0 # ?????????????0????
  ssl-protocol: SSLv3 # ?????HTTPS???SSL??????SSLv3
  logEnabled: true # ???????????true
